apiVersion: apps/v1
kind: Deployment
metadata:
  name: votacao-paredao-bbb-worker
  namespace: votacao-paredao-bbb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: votacao-paredao-bbb-worker
  template:
    metadata:
      labels:
        app: votacao-paredao-bbb-worker
    spec:
      containers:
        - name: worker
          image: votacao-paredao-bbb-worker:latest
          imagePullPolicy: IfNotPresent
          command:
            - /app/worker
          envFrom:
            - configMapRef:
                name: votacao-paredao-bbb-config
            - secretRef:
                name: votacao-paredao-bbb-secrets
          env:
            - name: DB_AUTO_MIGRATE
              value: "false"

---
apiVersion: v1
kind: Service
metadata:
  name: votacao-paredao-bbb-worker
  namespace: votacao-paredao-bbb
spec:
  selector:
    app: votacao-paredao-bbb-worker
  clusterIP: None

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: votacao-paredao-bbb-worker-pdb
  namespace: votacao-paredao-bbb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: votacao-paredao-bbb-worker
